# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/V2Ray
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/trojan 
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2     
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.txt
- type: subscribe
  options:
    url: https://qiaomenzhuanfx.netlify.app
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/online
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
- type: subscribe
  options:
    url: https://youlianboshi.netlify.com
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
- type: subscribe
  options:
    url: http://ss.pythonic.life/full/subscribe
- type: webfuzz
  options:    
    url: http://feeds.feedburner.com/mattkaydiary/pZjG    


# tg频道抓取
- type: tgchannel
  options:
    channel: KinhDownLoad
    num: 200
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/iwxf/free-v2ray/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html      
    
# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/shoujiyanxishe/atu/main/etsub.list
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list   
      
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
    
# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/skywolf627/VmessActions/main/subscribe/vmess.txt
