# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/V2Ray
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/trojan 
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2    
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/SSR.md
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/v2ray.md    
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.txt
    
#晓柒科技
- type: subscribe
  options:
    url: https://v2b.xiaoqikeji.tk/api/v1/client/subscribe?token=bc95c5e7b88fce68464c67039bd1c6e6
#JACKUSR2089
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/JACKUSR2089/v2ray-subscribed/master/subscribed/2021-9-22
#逍遥观世界   
- type: subscribe
  options:
    url: https://yun.xiaoyao01.com/dingyue/1fenxiang.txt
#工具大师
- type: subscribe
  options:
    url: http://121.4.209.91:8888/down/b6OPLBLTdci9

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/hugetiny/awesome-vpn/master/READMECN.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/iwxf/free-v2ray/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/xhrzg2017/xhrzg2017.github.io/master/v2.md   
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/JACKUSR2089/v2ray-subscribed/master/README.md
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html      
    
# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/shoujiyanxishe/atu/main/etsub.list
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list   
      
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
    
# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/shoujiyanxishe/atu/main/clash.yaml
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/skywolf627/VmessActions/main/subscribe/vmess.txt
- type: clash
  options:
    url: https://raw.githubusercontent.com/zyzmzyz/free-nodes/master/Clash.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.yml
    
#同行 
- type: clash
  options:
    url: https://proxypool-guest997.herokuapp.com/clash/proxies?type=ss,vmess,trojan&speed=5
   
