# 网页模糊抓取
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/hugetiny/awesome-vpn/master/READMECN.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/iwxf/free-v2ray/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
- type: clash
  options:
    url: https://raw.githubusercontent.com/shoujiyanxishe/atu/main/clash.yaml 
- type: clash
  options:
    url: https://www.233660.xyz/clash/proxies?type=vmess,trojan&new_name=true&speed=15 
- type: clash
  options:
    url: https://etproxypool.ga/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
- type: clash
  options:
    url: https://fq.lonxin.net/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
- type: clash
  options:
    url: https://sspool.nl/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
- type: clash
  options:
    url: https://freemby.tk/clash/proxies?type=vmess,trojan&new_name=true&speed=15       
- type: clash
  options:
    url: https://proxypool-guest997.herokuapp.com/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
