# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
- type: webfuzzsub
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed
- type: webfuzzsub
  options:
   url: http://d.zaix.ru/ntiL.txt
