# 订阅链接
- type: subscribe
  options:
    url: https://jiang.netlify.app    
- type: subscribe
  options:
    url: https://iwxf.netlify.app   
- type: subscribe
  options:
    url: https://youlianboshi.netlify.com
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/trojan 
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/SS.md
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/SSR.md
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/v2ray.md    
    
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
- type: clash
  options:
    url: https://raw.githubusercontent.com/shoujiyanxishe/atu/main/clash.yaml 
- type: clash
  options:
    url: https://www.233660.xyz/clash/proxies?type=vmess,trojan&new_name=true&speed=15 
- type: clash
  options:
    url: https://etproxypool.ga/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
- type: clash
  options:
    url: https://fq.lonxin.net/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
- type: clash
  options:
    url: https://sspool.nl/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
- type: clash
  options:
    url: https://freemby.tk/clash/proxies?type=vmess,trojan&new_name=true&speed=15       
- type: clash
  options:
    url: https://proxypool-guest997.herokuapp.com/clash/proxies?type=vmess,trojan&new_name=true&speed=15   
